/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThermometerRouteImport } from './routes/thermometer'
import { Route as IndexRouteImport } from './routes/index'

const ThermometerRoute = ThermometerRouteImport.update({
  id: '/thermometer',
  path: '/thermometer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/thermometer': typeof ThermometerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/thermometer': typeof ThermometerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/thermometer': typeof ThermometerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/thermometer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/thermometer'
  id: '__root__' | '/' | '/thermometer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThermometerRoute: typeof ThermometerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thermometer': {
      id: '/thermometer'
      path: '/thermometer'
      fullPath: '/thermometer'
      preLoaderRoute: typeof ThermometerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThermometerRoute: ThermometerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
